sudo: required
dist: trusty
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js: lts/*
branches:
  except:
    - master
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - yarn install
        - yarn test:ci