version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn'
      - run:
          name: install-dep
          command: yarn install && yarn test:ci